//STORES
export const STORES_LOAD_REQUEST = 'STORES_LOAD_REQUEST';
export const STORES_LOAD_SUCCESS = 'STORES_LOAD_SUCCESS';
export const STORES_LOAD_FAILURE = 'STORES_LOAD_FAILURE';

//STORE
export const STOREINFO_LOAD_REQUEST = 'STOREINFO_LOAD_REQUEST';
export const STOREINFO_LOAD_SUCCESS = 'STOREINFO_LOAD_SUCCESS';
export const STOREINFO_LOAD_FAILURE = 'STOREINFO_LOAD_FAILURE';

//MAPS
export const MAP_LOAD_REQUEST = 'MAP_LOAD_REQUEST';
export const MAP_LOAD_SUCCESS = 'MAP_LOAD_SUCCESS';
export const MAP_LOAD_FAILURE = 'MAP_LOAD_FAILURE';

//STORES CATEGORIES
export const CATEGORIES_LOAD_REQUEST = 'CATEGORIES_LOAD_REQUEST';
export const CATEGORIES_LOAD_SUCCESS = 'CATEGORIES_LOAD_SUCCESS';
export const CATEGORIES_LOAD_FAILURE = 'CATEGORIES_LOAD_FAILURE';

//PREFERENCES_CATEGORY
export const PREFERENCESCAT_LOAD_REQUEST = 'PREFERENCESCAT_LOAD_REQUEST';
export const PREFERENCESCAT_LOAD_SUCCESS = 'PREFERENCESCAT_LOAD_SUCCESS';
export const PREFERENCESCAT_LOAD_FAILURE = 'PREFERENCESCAT_LOAD_FAILURE';

export const PREFERENCESCAT_INSERT_REQUEST = 'PREFERENCESCAT_INSERT_REQUEST';
export const PREFERENCESCAT_INSERT_SUCCESS = 'PREFERENCESCAT_INSERT_SUCCESS';
export const PREFERENCESCAT_INSERT_FAILURE = 'PREFERENCESCAT_INSERT_FAILURE';

//RECOMMENDED_CATEGORIES
export const RECOMMENDEDCATEGORIES_LOAD_REQUEST = 'RECOMMENDEDCATEGORIES_LOAD_REQUEST';
export const RECOMMENDEDCATEGORIES_LOAD_SUCCESS = 'RECOMMENDEDCATEGORIES_LOAD_SUCCESS';
export const RECOMMENDEDCATEGORIES_LOAD_FAILURE = 'RECOMMENDEDCATEGORIES_LOAD_FAILURE';

//PRODUCTS CATEGORIES
export const PRODCATEGORIES_LOAD_REQUEST = 'PRODCATEGORIES_LOAD_REQUEST';
export const PRODCATEGORIES_LOAD_SUCCESS = 'PRODCATEGORIES_LOAD_SUCCESS';
export const PRODCATEGORIES_LOAD_FAILURE = 'PRODCATEGORIES_LOAD_FAILURE';

//PRODUCTS FAVOURITES
export const PRODFAVOURITES_LOAD_REQUEST = 'PRODFAVOURITES_LOAD_REQUEST';
export const PRODFAVOURITES_LOAD_SUCCESS = 'PRODFAVOURITES_LOAD_SUCCESS';
export const PRODFAVOURITES_LOAD_FAILURE = 'PRODFAVOURITES_LOAD_FAILURE';

//BANNERS
export const BANNERS_LOAD_REQUEST = 'BANNERS_LOAD_REQUEST';
export const BANNERS_LOAD_SUCCESS = 'BANNERS_LOAD_SUCCESS';
export const BANNERS_LOAD_FAILURE = 'BANNERS_LOAD_FAILURE';

//PRODUCTS
export const PRODUCTS_LOAD_REQUEST = 'PRODUCTS_LOAD_REQUEST';
export const PRODUCTS_LOAD_SUCCESS = 'PRODUCTS_LOAD_SUCCESS';
export const PRODUCTS_LOAD_FAILURE = 'PRODUCTS_LOAD_FAILURE';

//PRODUCTS_ADVANCED
export const PRODUCTSADVANCED_LOAD_REQUEST = 'PRODUCTSADVANCED_LOAD_REQUEST';
export const PRODUCTSADVANCED_LOAD_SUCCESS = 'PRODUCTSADVANCED_LOAD_SUCCESS';
export const PRODUCTSADVANCED_LOAD_FAILURE = 'PRODUCTSADVANCED_LOAD_FAILURE';

//INCIDENTS
export const INCIDENTS_LOAD_REQUEST = 'INCIDENTS_LOAD_REQUEST';
export const INCIDENTS_LOAD_SUCCESS = 'INCIDENTS_LOAD_SUCCESS';
export const INCIDENTS_LOAD_FAILURE = 'INCIDENTS_LOAD_FAILURE';
export const INCIDENTS_INSERT_REQUEST = 'INCIDENTS_INSERT_REQUEST';
export const INCIDENTS_INSERT_SUCCESS = 'INCIDENTS_INSERT_SUCCESS';
export const INCIDENTS_INSERT_FAILURE = 'INCIDENTS_INSERT_FAILURE';

//PROFILE
export const PROFILE_LOAD_REQUEST = 'PROFILE_LOAD_REQUEST';
export const PROFILE_LOAD_SUCCESS = 'PROFILE_LOAD_SUCCESS';
export const PROFILE_LOAD_FAILURE = 'PROFILE_LOAD_FAILURE';

//ROUTE
export const ROUTE_LOAD_REQUEST = 'ROUTE_LOAD_REQUEST';
export const ROUTE_LOAD_SUCCESS = 'ROUTE_LOAD_SUCCESS';
export const ROUTE_LOAD_FAILURE = 'ROUTE_LOAD_FAILURE';

export const PROFILE_EDIT_REQUEST = 'PROFILE_EDIT_REQUEST';
export const PROFILE_EDIT_SUCCESS = 'PROFILE_EDIT_SUCCESS';
export const PROFILE_EDIT_FAILURE = 'PROFILE_EDIT_FAILURE';

//EVENTS
export const EVENTS_LOAD_REQUEST = 'EVENTS_LOAD_REQUEST';
export const EVENTS_LOAD_SUCCESS = 'EVENTS_LOAD_SUCCESS';
export const EVENTS_LOAD_FAILURE = 'EVENTS_LOAD_FAILURE';

//ACHIEVEMENTS
export const ACHIEVEMENTS_LOAD_REQUEST = 'ACHIEVEMENTS_LOAD_REQUEST';
export const ACHIEVEMENTS_LOAD_SUCCESS = 'ACHIEVEMENTS_LOAD_SUCCESS';
export const ACHIEVEMENTS_LOAD_FAILURE = 'ACHIEVEMENTS_LOAD_FAILURE';

//BATHROOMS
export const BATHROOM_LOAD_REQUEST = 'BATHROOM_LOAD_REQUEST';
export const BATHROOM_LOAD_SUCCESS = 'BATHROOM_LOAD_SUCCESS';
export const BATHROOM_LOAD_FAILURE = 'BATHROOM_LOAD_FAILURE';

//BATHROOMS
export const HELPCENTER_LOAD_REQUEST = 'HELPCENTER_LOAD_REQUEST';
export const HELPCENTER_LOAD_SUCCESS = 'HELPCENTER_LOAD_SUCCESS';
export const HELPCENTER_LOAD_FAILURE = 'HELPCENTER_LOAD_FAILURE';
